In [1]:
import torch

print(torch.__version__)

2.2.2


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [4]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
torch.is_tensor(tensor_arr)

True

In [6]:
torch.numel(tensor_arr)

6

In [7]:
tensor_uninitialized = torch.Tensor(2,2)
tensor_uninitialized

tensor([[0., 0.],
        [0., 0.]])

In [8]:
tensor_initialized = torch.rand(2,3)
tensor_initialized

tensor([[0.5303, 0.2320, 0.9887],
        [0.8276, 0.9775, 0.1976]])

In [9]:
tensor_custom = torch.tensor([[2,4],[3,1]]).type(torch.IntTensor)
tensor_custom

tensor([[2, 4],
        [3, 1]], dtype=torch.int32)

In [10]:
tensor_short = torch.ShortTensor([1,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [11]:
tensor_float = torch.tensor([1,2,3]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [12]:
tensor_fill = torch.full((2,5), fill_value=14)
tensor_fill

tensor([[14, 14, 14, 14, 14],
        [14, 14, 14, 14, 14]])

In [13]:
tensor_of_ones = torch.ones([2,6], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [14]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=torch.int32)

In [15]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
non_zero_indicies = torch.nonzero(tensor_eye)
non_zero_indicies

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [17]:
indicies = torch.tensor([[0,1,1], [2,2,0]])
indicies

tensor([[0, 1, 1],
        [2, 2, 0]])

In [18]:
values = torch.tensor([3,4,5], dtype=torch.float32)
values

tensor([3., 4., 5.], dtype=torch.float32)

In [19]:
sparce_tensor = torch.sparse_coo_tensor(indicies, values, [2,5])
sparce_tensor

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [20]:
dence_tensor = sparce_tensor.to_dense()
dence_tensor

tensor([[0., 0., 3., 0., 0.],
        [5., 0., 4., 0., 0.]], dtype=torch.float32)

In [21]:
initial = torch.randint(0, 10, (4, 2))
initial

tensor([[5, 5],
        [4, 7],
        [7, 2],
        [7, 8]])

In [22]:
initial.add(5) # creates new tensor and returns

tensor([[10, 10],
        [ 9, 12],
        [12,  7],
        [12, 13]])

In [23]:
initial

tensor([[5, 5],
        [4, 7],
        [7, 2],
        [7, 8]])

In [24]:
initial.add_(5) # changes current tensor like extension method

tensor([[10, 10],
        [ 9, 12],
        [12,  7],
        [12, 13]])

In [25]:
initial

tensor([[10, 10],
        [ 9, 12],
        [12,  7],
        [12, 13]])

In [26]:
sqrt = initial.sqrt()
sqrt

tensor([[3.1623, 3.1623],
        [3.0000, 3.4641],
        [3.4641, 2.6458],
        [3.4641, 3.6056]])

In [27]:
equal_space = torch.linspace(1, 10, 15)
equal_space

tensor([ 1.0000,  1.6429,  2.2857,  2.9286,  3.5714,  4.2143,  4.8571,  5.5000,
         6.1429,  6.7857,  7.4286,  8.0714,  8.7143,  9.3571, 10.0000])

In [28]:
tensor_chunk = torch.chunk(equal_space, 3)
tensor_chunk

(tensor([1.0000, 1.6429, 2.2857, 2.9286, 3.5714]),
 tensor([4.2143, 4.8571, 5.5000, 6.1429, 6.7857]),
 tensor([ 7.4286,  8.0714,  8.7143,  9.3571, 10.0000]))

In [29]:
tensor1 = tensor_chunk[0]
tensor2 = torch.tensor([2,3,4])
tensor3 = tensor_chunk[2]

torch.cat((tensor1, tensor2, tensor3))

tensor([ 1.0000,  1.6429,  2.2857,  2.9286,  3.5714,  2.0000,  3.0000,  4.0000,
         7.4286,  8.0714,  8.7143,  9.3571, 10.0000])

In [30]:
random = torch.randint(0, 10, (4,3))
random

tensor([[1, 5, 9],
        [0, 2, 9],
        [4, 0, 0],
        [9, 8, 5]])

In [31]:
random[0,1]

tensor(5)

In [32]:
random[0:, 1:]

tensor([[5, 9],
        [2, 9],
        [0, 0],
        [8, 5]])

In [33]:
random[0:, 1:].size()

torch.Size([4, 2])

In [34]:
resized_view = random.view(2,6) # view function does not create a new memory, its just like DB view
resized_view

tensor([[1, 5, 9, 0, 2, 9],
        [4, 0, 0, 9, 8, 5]])

In [35]:
resized_view[0,4] = 14
resized_view

tensor([[ 1,  5,  9,  0, 14,  9],
        [ 4,  0,  0,  9,  8,  5]])

In [36]:
random

tensor([[ 1,  5,  9],
        [ 0, 14,  9],
        [ 4,  0,  0],
        [ 9,  8,  5]])

In [37]:
initial = torch.randint(0,10,(2, 3, 4))
initial

tensor([[[1, 6, 6, 9],
         [9, 8, 9, 2],
         [8, 1, 4, 9]],

        [[2, 5, 9, 8],
         [7, 7, 7, 4],
         [9, 9, 3, 9]]])

In [38]:
initial.shape

torch.Size([2, 3, 4])

In [39]:
# add empty dimension at index
initial = torch.unsqueeze(initial, 3)
initial = torch.unsqueeze(initial, 2)
initial = torch.unsqueeze(initial, 1)
initial = torch.unsqueeze(initial, 0)
initial.shape

torch.Size([1, 2, 1, 3, 1, 4, 1])

In [40]:
# remove empty dimension at index
initial = torch.squeeze(initial, 2)
initial.shape

torch.Size([1, 2, 3, 1, 4, 1])

In [41]:
# remove all empty dimensions
initial = torch.squeeze(initial)
initial.shape

torch.Size([2, 3, 4])

In [42]:
torch.transpose(initial, 0, 1) # swap dimensions at indexes

tensor([[[1, 6, 6, 9],
         [2, 5, 9, 8]],

        [[9, 8, 9, 2],
         [7, 7, 7, 4]],

        [[8, 1, 4, 9],
         [9, 9, 3, 9]]])

In [43]:
torch.sort(initial) # by default sorts last dimension

torch.return_types.sort(
values=tensor([[[1, 6, 6, 9],
         [2, 8, 9, 9],
         [1, 4, 8, 9]],

        [[2, 5, 8, 9],
         [4, 7, 7, 7],
         [3, 9, 9, 9]]]),
indices=tensor([[[0, 1, 2, 3],
         [3, 1, 0, 2],
         [1, 2, 0, 3]],

        [[0, 1, 3, 2],
         [3, 0, 1, 2],
         [2, 0, 1, 3]]]))

In [44]:
integers = torch.randint(-9, 9, (3,2))
integers

tensor([[-3,  0],
        [-4,  3],
        [-3, -2]])

In [45]:
integers.abs()

tensor([[3, 0],
        [4, 3],
        [3, 2]])