In [1]:
import torch

In [2]:
a = torch.randint(1, 9, (2, 4))
b = torch.randint(1, 9, (2, 4))
c = torch.add(a, b)
c

tensor([[ 9, 13,  6,  6],
        [ 4,  9, 11,  6]])

In [3]:
torch.div(a, c)

tensor([[0.7778, 0.4615, 0.1667, 0.8333],
        [0.7500, 0.3333, 0.7273, 0.3333]])

In [4]:
torch.mul(c, c)

tensor([[ 81, 169,  36,  36],
        [ 16,  81, 121,  36]])

In [5]:
torch.clamp(c, min=5, max=9)

tensor([[9, 9, 6, 6],
        [5, 9, 9, 6]])

In [6]:
a

tensor([[7, 6, 1, 5],
        [3, 3, 8, 2]])

In [7]:
b.transpose(0,1)

tensor([[2, 1],
        [7, 6],
        [5, 3],
        [1, 4]])

In [8]:
torch.matmul(a[0:,2:],b[0:,2:]) # multi dimension

tensor([[20, 21],
        [46, 16]])

In [9]:
v1 = torch.tensor([1, 2, 3, 4])
v2 = torch.tensor([2, 3, 4, 5])
torch.dot(v1, v2) # single dimension

tensor(40)

In [10]:
matrix_vector = torch.mv(a, v1)
matrix_vector

tensor([42, 41])

In [11]:
matrix_mul = torch.mm(a, b.transpose(0,1))
matrix_mul

tensor([[66, 66],
        [69, 53]])

In [12]:
c

tensor([[ 9, 13,  6,  6],
        [ 4,  9, 11,  6]])

In [13]:
indicies = c.argmax(0) # maximums in dimension 0
indicies

tensor([0, 0, 1, 0])

In [14]:
indicies = c.argmax(1) # maximums in dimension 1
indicies

tensor([1, 2])

In [15]:
index = c.argmax() # maximum in entire set
index

tensor(1)

In [16]:
maxs = c.max(0) # maximums in dimension 0
maxs

torch.return_types.max(
values=tensor([ 9, 13, 11,  6]),
indices=tensor([0, 0, 1, 0]))