In [4]:
import numpy as np
import torch

In [6]:
t = torch.rand(4,3)
t # this can be executed on GPUs

tensor([[0.0913, 0.2227, 0.4520],
        [0.6387, 0.3716, 0.6379],
        [0.0554, 0.8899, 0.4893],
        [0.0611, 0.4982, 0.4076]])

In [7]:
type(t)

torch.Tensor

In [9]:
a = t.numpy() # both share the same memory
a # this cannot be executed on GPUs

array([[0.091254  , 0.22271812, 0.45203382],
       [0.63873565, 0.37164676, 0.6379075 ],
       [0.0554384 , 0.88989574, 0.48929954],
       [0.0610913 , 0.4982195 , 0.4075622 ]], dtype=float32)

In [10]:
type(a)

numpy.ndarray

In [11]:
torch.is_tensor(a)

False

In [15]:
torch.is_tensor(t)

True

In [18]:
a[0,0] = 111
a

array([[1.1100000e+02, 2.2271812e-01, 4.5203382e-01],
       [6.3873565e-01, 3.7164676e-01, 6.3790751e-01],
       [5.5438399e-02, 8.8989574e-01, 4.8929954e-01],
       [6.1091304e-02, 4.9821949e-01, 4.0756220e-01]], dtype=float32)

In [19]:
t

tensor([[1.1100e+02, 2.2272e-01, 4.5203e-01],
        [6.3874e-01, 3.7165e-01, 6.3791e-01],
        [5.5438e-02, 8.8990e-01, 4.8930e-01],
        [6.1091e-02, 4.9822e-01, 4.0756e-01]])

In [21]:
a = np.random.rand(3,4)
a

array([[0.31424543, 0.01476999, 0.55404347, 0.33842763],
       [0.94621036, 0.36936783, 0.78898212, 0.56009893],
       [0.16355441, 0.47683564, 0.55172876, 0.49297097]])

In [22]:
t = torch.from_numpy(a) # both share the same memory
t

tensor([[0.3142, 0.0148, 0.5540, 0.3384],
        [0.9462, 0.3694, 0.7890, 0.5601],
        [0.1636, 0.4768, 0.5517, 0.4930]], dtype=torch.float64)

In [23]:
t1= torch.as_tensor(a) # memory allocation depends on type, dtype and device, use it to avoid unnecessary memory copies
t1

tensor([[0.3142, 0.0148, 0.5540, 0.3384],
        [0.9462, 0.3694, 0.7890, 0.5601],
        [0.1636, 0.4768, 0.5517, 0.4930]], dtype=torch.float64)

In [24]:
t2= torch.tensor(a) # new memory will be allocated
t2

tensor([[0.3142, 0.0148, 0.5540, 0.3384],
        [0.9462, 0.3694, 0.7890, 0.5601],
        [0.1636, 0.4768, 0.5517, 0.4930]], dtype=torch.float64)