In [0]:
import torch

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.cuda.current_device()

0

In [6]:
torch.cuda.device_count()

1

In [7]:
# Use this function to monitor CUDA memory occupied by the tensors you allocate
torch.cuda.memory_allocated()

0

In [8]:
# Behind the scenes PyTorch uses a cachin memory allocator to speed up memory allocations - this allows fast memory deallocation without device synchronizations
torch.cuda.memory_cached()

0

In [9]:
cuda = torch.device('cuda')
cuda

device(type='cuda')

In [0]:
cuda0 = torch.device('cuda:0')

In [11]:
# On CPU
x = torch.tensor([10, 20])
x

tensor([10, 20])

In [13]:
x_default = torch.tensor([10, 20], device=cuda)
x_default

tensor([10, 20], device='cuda:0')

In [14]:
x0 = torch.tensor([10, 20], device=cuda0)
x0

tensor([10, 20], device='cuda:0')

In [15]:
x1 = torch.tensor([10, 20], device=cuda1)

NameError: ignored

In [16]:
# to bring tensor from CPU to GPU
y = x.cuda()
y

tensor([10, 20], device='cuda:0')

In [18]:
print('Outside with context: ', torch.cuda.current_device())

with torch.cuda.device(0):

  print('Inside with context: ', torch.cuda.current_device())

print('Outside with context again: ', torch.cuda.current_device())

Outside with context:  0
Inside with context:  0
Outside with context again:  0


In [0]:
torch.device('cpu')
with torch.cuda.device(0):
  a = torch.tensor([10, 20])
  a0 = torch.tensor([10, 20], device=cuda0)
  a1 = torch.tensor([10,20], device='cpu')

In [24]:
a

tensor([10, 20])

In [25]:
a0

tensor([10, 20], device='cuda:0')

In [26]:
a1

tensor([10, 20])

In [0]:
b1 = a0.to(device=cuda1)

In [0]:
# Operations cannot be peformed on tensors on different CUDA devices

In [30]:
torch.cuda.memory_allocated()

3072

In [31]:
torch.cuda.memory_cached()

2097152

In [0]:
torch.cuda.empty_cache() #Gets rid of UNUSED memory in cached

In [33]:
torch.cuda.memory_cached()

2097152

In [34]:
# Operations prefixed with "new_" create new tensors of the same type on the same device
preserve_context = x.new_full([2,2], fill_value=1.1)
preserve_context

tensor([[1, 1],
        [1, 1]])

In [35]:
preserve_context0 = x0.new_full([2,2], fill_value=1.1)
preserve_context0

tensor([[1, 1],
        [1, 1]], device='cuda:0')