In [1]:
import torch

In [3]:
t1 = torch.rand(3,4) * 10
t1

tensor([[9.3282, 3.5274, 4.8635, 2.8723],
        [3.7953, 2.5294, 1.4086, 3.9868],
        [4.1560, 5.6738, 9.0083, 7.2372]])

In [4]:
t2 = torch.rand(3,4) * 10
t2

tensor([[2.1291, 1.5009, 7.4483, 7.6864],
        [0.8085, 9.6288, 5.0776, 9.2781],
        [6.9175, 4.5585, 4.5989, 4.8418]])

In [5]:
t1.requires_grad_()

tensor([[9.3282, 3.5274, 4.8635, 2.8723],
        [3.7953, 2.5294, 1.4086, 3.9868],
        [4.1560, 5.6738, 9.0083, 7.2372]], requires_grad=True)

In [6]:
t = t1 * t2
t

tensor([[19.8608,  5.2943, 36.2247, 22.0776],
        [ 3.0684, 24.3553,  7.1524, 36.9899],
        [28.7493, 25.8637, 41.4284, 35.0412]], grad_fn=<MulBackward0>)

In [7]:
print(t1.requires_grad)
print(t2.requires_grad)
print(t.requires_grad)

True
False
True


In [8]:
print(t1.grad)
print(t2.grad)
print(t.grad)

None
None
None


/var/folders/ys/d2pd89m53_n3_pyzbqfc850w0000gn/T/ipykernel_28119/1979799225.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(t.grad)


In [9]:
print(t1.grad_fn)
print(t2.grad_fn)
print(t.grad_fn)

None
None


In [10]:
t = (t1 * t2).mean()
t.grad_fn

In [11]:
print(t1.grad)
print(t2.grad)
print(t.grad)

None
None
None


/var/folders/ys/d2pd89m53_n3_pyzbqfc850w0000gn/T/ipykernel_28119/1979799225.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(t.grad)


In [12]:
t.backward()

In [13]:
print(t1.grad)
print(t2.grad)
print(t.grad)

tensor([[0.1774, 0.1251, 0.6207, 0.6405],
        [0.0674, 0.8024, 0.4231, 0.7732],
        [0.5765, 0.3799, 0.3832, 0.4035]])
None
None


/var/folders/ys/d2pd89m53_n3_pyzbqfc850w0000gn/T/ipykernel_28119/1979799225.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(t.grad)


In [14]:
with torch.no_grad():
    t = t1 * 3
    print(f'result tensor: {t}')
    print(f'requires_grad for t1: {t1.requires_grad}')
    print(f'requires_grad for t2: {t2.requires_grad}')
    print(f'requires_grad for t: {t.requires_grad}')


result tensor: tensor([[27.9845, 10.5821, 14.5904,  8.6169],
        [11.3858,  7.5883,  4.2258, 11.9604],
        [12.4680, 17.0213, 27.0250, 21.7116]])
requires_grad for t1: True
requires_grad for t2: False
requires_grad for t: False


In [15]:
def calculate(t):
    return t * 2

In [16]:
@torch.no_grad()
def calculate_no_grad(t):
    return t * 2

In [17]:
calculate(t1)

tensor([[18.6563,  7.0547,  9.7270,  5.7446],
        [ 7.5905,  5.0589,  2.8172,  7.9736],
        [ 8.3120, 11.3476, 18.0166, 14.4744]], grad_fn=<MulBackward0>)

In [18]:
calculate_no_grad(t2)

tensor([[ 4.2582,  3.0018, 14.8966, 15.3728],
        [ 1.6170, 19.2576, 10.1553, 18.5561],
        [13.8350,  9.1169,  9.1978,  9.6836]])

In [19]:
with torch.no_grad():
    t = t1 * 5
    print(t)
    with torch.enable_grad():
        t = t1 * 6
        print(t)

tensor([[46.6408, 17.6368, 24.3174, 14.3615],
        [18.9763, 12.6471,  7.0431, 19.9340],
        [20.7801, 28.3689, 45.0416, 36.1860]])
tensor([[55.9689, 21.1642, 29.1809, 17.2338],
        [22.7715, 15.1766,  8.4517, 23.9209],
        [24.9361, 34.0427, 54.0499, 43.4231]], grad_fn=<MulBackward0>)


In [20]:
t_buf = torch.tensor([[1.8245, 3.7843, 9.4944],
        [2.8990, 7.7309, 6.1554]]).multiply(10)
t_one = torch.tensor(t_buf, requires_grad=True)
# t_one = t_one.multiply(10)
print(t_one.requires_grad)
print(t_one.grad_fn)
# t_one.requires_grad_()
t_one

True
None


/var/folders/ys/d2pd89m53_n3_pyzbqfc850w0000gn/T/ipykernel_28119/2463847826.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t_one = torch.tensor(t_buf, requires_grad=True)


tensor([[18.2450, 37.8430, 94.9440],
        [28.9900, 77.3090, 61.5540]], requires_grad=True)

In [21]:
t_two = torch.rand(2,3) * 10
print(t_two.requires_grad)
print(t_two.grad_fn)
t_two.requires_grad_()
t_two

False
None


tensor([[5.1511, 4.5034, 7.4889],
        [8.2414, 9.7214, 0.0734]], requires_grad=True)

In [22]:
print(t_one.grad)
print(t_two.grad)

None
None


In [23]:
result = (t_one + t_two).mean()
result

tensor(59.0108, grad_fn=<MeanBackward0>)

In [24]:
print(t_one.requires_grad)
print(t_two.requires_grad)

True
True


In [25]:
result.backward()
print(t_one.grad)
print(t_two.grad)

tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])
tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])


In [26]:
detached = torch.detach(t_one)
detached

tensor([[18.2450, 37.8430, 94.9440],
        [28.9900, 77.3090, 61.5540]])

In [27]:
detached.requires_grad

False

In [28]:
result = (t_one + detached).mean()
result

tensor(106.2950, grad_fn=<MeanBackward0>)

In [29]:
result.backward()
print(t_one.grad)
print(detached.grad)

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])
None
